[package]
name = "panty"
version = "0.1.0"
authors = ["anekos <anekos@snca.net>"]

[dependencies]
argparse = "*"
log = "*"
env_logger = "*"
lazy_static = "*"
libc = "*"
unix_socket = "*"
x11 = { version = "*", features = ["xlib", "xinerama"] }
rustc-serialize = "*"
inotify = "*"
