#!/bin/bash

##############################################################
# .-,--.   ,.  ,-,-.  ,--,--'.  .       ,.  ,-,-.   .-,--.   #
#  '|__/  / |  ` | |  `- |   |  |      / |  ` | |   ' |   \  #
#  ,|    /~~|-.  | |-. , |   |  |     /~~|-.  | |-. , |   /  #
#  `'  ,'   `-' ,' `-' `-'   `--|   ,'   `-' ,' `-' `-^--'   #
#                            .- |                            #
#                            `--'                            #
# .---. ,--,--',,--.  ,--. ,-, , ,-_/ ,-,-.   ,---.          #
# \___  `- |   |`, | | `-'  )|/  '  | ` | |   |  -'          #
#     \  , |   |   | |   .   |\  .^ |   | |-. |  ,-'         #
# `---'  `-'   `---' `--'   ,' ` `--'  ,' `-' `---|          #
#                                              ,-.|          #
#                                              `-+'          #
##############################################################

next_role_number=1
max_stockings=10
inotify_event_delay=0.3


function new_role () {
  next_role_number=$(( next_role_number + 1))
}

function get_role () {
  local wid="$1"
  xprop -id "$wid" -f WM_WINDOW_ROLE 8s WM_WINDOW_ROLE | sed 's/[^"]*"//' | sed 's/"$//' | grep -v 'not found'
}

function get_gvims () {
  xdotool search --class 'gvim'
}

# print "$window $role"
function get_stockings () {
  xdotool search --class 'gvim' | while read window
  do
    local role="$(get_role "$window")"
    [[ $role =~ ^STOCKING-[0-9]+$ ]] && echo "$window:$role"
  done
}

function initialize () {
  # set next_role_number
  local current_stockings=0

  for found in `get_stockings`
  do
    local role="${found#*:}"
    local number=${role#*-}
    local current_stockings=$(( current_stockings + 1 ))
    [[ $number -ge $next_role_number ]] && next_role_number=$(( number + 1 ))
  done

  for nop in `seq $(( max_stockings - current_stockings ))`
  do
    spawn
  done
}

function find_stocking () {
  get_stockings | head -n 1
}

function spawn () {
  local name="STOCKING-$next_role_number"

  echo "spawn: $name"
  gvim --role "$name" --servername "$name"

  next_role_number=$(( next_role_number + 1 ))
}

function kill_em_all () {
  for found in `get_stockings`
  do
    local window="${found%:*}"
    xdotool windowkill "$window"
  done
}

function main_initialize () {
  initialize
}

function main_restart () {
  kill_em_all
  initialize
}

function main_daemon () {
  if [ "${#@}" -eq 0 ]
  then
    local targets=(~/.vimrc ~/.vim)
  else
    local targets=("$@")
  fi

  echo "daemon: ${targets[@]}"
  inotifywait -e move,delete,close_write  -r "${targets[@]}"
  sleep "$inotify_event_delay"
  main_restart
  main_daemon "$@"
}

function main_summon () {
  local found="$(find_stocking)"
  local desktop="$(xdotool get_desktop)"

  if [ -z "$found" ]
  then
    echo 'Stocking Not Found' 1>&2
    initialize
    local found="$(find_stocking)"
  fi

  [ -z "$found" ] && exit 1

  local window="${found%:*}"
  local role="${found#*:}"

  echo "summon: $role"

  # Move a stockin to current workspace
  xdotool set_desktop_for_window "$window" "$desktop"

  # Send file names
  [ "$#" -gt 0 ] && gvim --servername "$role" --remote "$@"

  # Stocking becomes panty
  xdotool set_window --role 'PANTY' "$window"

  initialize
}

function main () {
  local sub="$1"
  shift

  if [ -n "$sub" ] && type "main_$sub" &> /dev/null
  then
    "main_$sub" "$@"
    exit 0
  fi

  exec 2>&1
  echo "Usage: panty summon <GVIM ARGS>...."
  echo "       panty initialize"
  echo "       panty restart"
  exit 1
}

main "$@"


# The MIT License (MIT)
#
# Copyright (c) anekos <panty-of-anekos@snca.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
