#!/bin/bash

# set -euC
# set -x

if [ -f RUNNING_PID ]
then
  kill "$(cat RUNNING_PID)" ||:
  rm RUNNING_PID
fi

RUST_LOG=trace ./target/debug/panty collector --stocks 5 --watch ~/.vimrc --recursive-watch ~/.vim/part/ --current-directory /tmp/xmosh &
echo "$!" >> RUNNING_PID
