#!/bin/bash

# set -euC
# set -x

if [ -f RUNNING_PID ]
then
  kill "$(cat RUNNING_PID)" ||:
  rm RUNNING_PID
fi

[ -e stockings ] && rm stockings

./target/debug/panty collector &
echo "$!" >> RUNNING_PID
